version: "3"
services:
  postal:
    image: catdeployed/postal:alpine
    container_name: postal
    command: run
    ports:
      - 127.0.0.1:25:25
    depends_on:
      - "mysql"
      - "rabbitmq"
    volumes:
      - static_assets:/opt/postal/public
      - ./data/postal/assets:/opt/postal/public/assets
      - ./src/templates/:/templates
    environment:
      - MYSQL_ROOT_PASSWORD=changeme
      - MYSQL_DATABASE=postal
      - RABBITMQ_DEFAULT_USER=postal
      - RABBITMQ_DEFAULT_PASS=changeme
      - RABBITMQ_DEFAULT_VHOST=postal
      - MX_HOSTNAME=mx.postal.example.com
      - SMTP_HOSTNAME=postal.example.com
      - SPF_HOSTNAME=spf.example.com
      - RP_HOSTNAME=rp.example.com
      - ROUTE_HOSTNAME=route.example.com
      - TRACK_HOSTNAME=track.example.com
  mysql:
    image: mariadb:10
    container_name: postal_mysql
    volumes:
      - ./data/mysql:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=changeme
      - MYSQL_DATABASE=postal
  rabbitmq:
    image: rabbitmq:3-alpine
    container_name: postal_rabbitmq
    environment:
      - RABBITMQ_DEFAULT_USER=postal
      - RABBITMQ_DEFAULT_PASS=changeme
      - RABBITMQ_DEFAULT_VHOST=/postal
  nginx:
    image: nginx
    container_name: postal_nginx
    ports:
      - 0.0.0.0:80:80
    links:
      - postal
    depends_on:
      - postal
    volumes:
      - ./src/nginx.conf:/etc/nginx/conf.d/default.conf:ro
      - static_assets:/opt/postal/public:ro
      - ./data/postal/assets:/opt/postal/public/assets:ro
volumes:
  static_assets:

